### ISSUE TITLE
PHP 7.4 required?

### ISSUE THREAD

**Issue by MykolaKovrizhnykh** [rinvex/laravel-contacts#7]
Hi. Why PHP 7.4 is required?

I use alpine build https://pkgs.alpinelinux.org/packages?name=php7&branch=v3.12

and here only 7.3 available? Can your package be used with 7.3? How can I downgrade required version?

**Comment by Omranic** [comment]
Yes, you can use v3.x of this package which requires at least PHP v7.2 🙂  Happy coding!

**Comment by MykolaKovrizhnykh** [comment]
But I can't use it with laravel 7 if I use v3 :( @Omranic

**Comment by Omranic** [comment]
I see, then in that case you can for the package and lower the PHP version to your needs

**Comment by MykolaKovrizhnykh** [comment]
> I see, then in that case you can for the package and lower the PHP version to your needs

But this package have other dependencies, that require php 7.4: countries, support, etc..

Bad news :(

**Comment by MykolaKovrizhnykh** [comment]
@Omranic , maybe you can add support laravel v7 for contacts and addresses v3, because I use them in my project and have much code depends on this libraries. If you can.
